version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - /portainer/mongo:/data/db
    ports:
    - '27017:27017'

  mongo-express: 
    container_name: mongo-express
    image: mongo-express
    ports: 
    - '8081:8081'